version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    # environment:
    #   - PYTHONDONTWRITEBYTECODE=1
    #   - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: fastapi run app/main.py

  tests:
    build: .
    # environment:
    #   - PYTHONDONTWRITEBYTECODE=1
    #   - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: pytest -v
