services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

  tests:
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: pytest -v
